#!/usr/bin/env bash
# Configure your Nginx server

apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

sed -i '/listen 80 default_server;/a \    rewrite ^/redirect_me https://example.com/ permanent;' /etc/nginx/sites-available/default
service nginx restart
