#!/usr/bin/env bash
# Configure your Nginx server

apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

sed -i '/listen 80 default_server;/a \    rewrite ^/redirect_me https://example.com/ permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

service nginx restart
