#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task

hostname=$(hostname)

apt-get update
apt-get install -y nginx

sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.example.com permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

sed -i "41i add_header X-Served-By $hostname;" /etc/nginx/sites-available/default

service nginx restart
