#!/bin/bash
# Using what you did for task #0, make your fix short and sweet.
apt-get update
apt-get install -y nginx
echo -e "server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\troot /var/www/html;\n\tindex index.html index.htm index.nginx-debian.html;\n\tserver_name _;\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n}" > /etc/nginx/sites-available/default
nginx

