#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hour=1
minute=1
echo "Hour: 0"
while [[ $hour -le 12 || $minute -le 59 ]]
do
	if [ $minute -eq 60 ]
	then
		echo "Hour: $hour"
		minute=1
		hour=$(( hour + 1 ))
	fi
	echo "$minute"
	minute=$(( minute + 1 ))
done
